// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsBxLs7vLmyLA1q6ShaZ2_KXef6mVdrsU',
    appId: '1:588867274755:web:651bcade4a35e47a82a636',
    messagingSenderId: '588867274755',
    projectId: 'rewriter-app-d511c',
    authDomain: 'rewriter-app-d511c.firebaseapp.com',
    storageBucket: 'rewriter-app-d511c.firebasestorage.app',
    measurementId: 'G-LD21L2X2HD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxwjMfVYybAU8ffrtUgu_q31qnOku6uh4',
    appId: '1:588867274755:android:8c1c81457936b2c782a636',
    messagingSenderId: '588867274755',
    projectId: 'rewriter-app-d511c',
    storageBucket: 'rewriter-app-d511c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZczqMSFxdUFOqNO2rkIvbg-oE6Yw_c94',
    appId: '1:588867274755:ios:1a7219eaa8bdd05c82a636',
    messagingSenderId: '588867274755',
    projectId: 'rewriter-app-d511c',
    storageBucket: 'rewriter-app-d511c.firebasestorage.app',
    iosBundleId: 'com.example.rewriter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZczqMSFxdUFOqNO2rkIvbg-oE6Yw_c94',
    appId: '1:588867274755:ios:1a7219eaa8bdd05c82a636',
    messagingSenderId: '588867274755',
    projectId: 'rewriter-app-d511c',
    storageBucket: 'rewriter-app-d511c.firebasestorage.app',
    iosBundleId: 'com.example.rewriter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsBxLs7vLmyLA1q6ShaZ2_KXef6mVdrsU',
    appId: '1:588867274755:web:874f421f0258a6b282a636',
    messagingSenderId: '588867274755',
    projectId: 'rewriter-app-d511c',
    authDomain: 'rewriter-app-d511c.firebaseapp.com',
    storageBucket: 'rewriter-app-d511c.firebasestorage.app',
    measurementId: 'G-BY6MBSSC5Y',
  );
}
